spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/olxtableschema
        username: root
        password: 3548

    jpa:
        generate-ddl: true
        show-sql: true
        
        hibernate:
            ddl-auto: create
            dialect: org.hibernate.dialect.MySQL8Dialect
